#!/bin/bash
# Runs application and relevant containers in docker
# You can pass your argument like so:
# ./run-project

./backend

# Command to which options will be appended
npm_build_command="docker-compose run --rm --service-ports npm run dev"

# Execute the command
eval $npm_build_command