#!/bin/bash
# Runs application and relevant containers in docker
# You can use it like so:
# ./run-project

docker_services="docker-compose up -d nginx"

eval $docker_services

# Command to which options will be appended
npm_build_command="docker-compose run --rm --service-ports npm run dev"

# Execute the command
eval $npm_build_command